In [ ]:
# Dummy variables

In [21]:
# data processing
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

X = dataset.iloc[:, 3:13].values  # gets values from 3 to 12 (remember that 13 is not included) # puts into numpy array
y = dataset.iloc[:,13].values # we put thirteen  for row thirteen here

dataset.head(5)

print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [22]:
# because we have some categorical variables in our data, we need to turn them into numbers
# I could use column transform with this 


# Encoding categorical data
# are data contains two columns with categorical data
# There is column 1 which has the countries 'France','Spain,'and German
# There is also the other column which is 'Male' or 'Female'

# We will start with countries
# Sincer th
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Let's use a function to do this. We will use labelencoder_X_1. 
labelencoder_X_1 = LabelEncoder() # This turn france, germany,spain into 0,1, and 2

# let's get the right part of the data to change. We are changing the 1 column
X[:,1] = labelencoder_X_1.fit_transform(X[:,1]) 


# Now let's do the same for the gender
labelencoder_X_2 = LabelEncoder()

# Now let's make the change
X[:,2] = labelencoder_X_1.fit_transform(X[:,2]) 

# There is a problem though. We need to make sure our variables are not higher than each based on these number
# that we just gave them. To do this we will create dummy variables
onehotencoder = OneHotEncoder(categorical_features = [1])  # 1 is for the column we are making dummy variables off of
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]


print(X)

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


C:\Users\Natha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Natha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [27]:
# how can I use column transform instead?
from sklearn.compose import ColumnTransformer

# rerun all this code
# data processing
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

X = dataset.iloc[:, 3:13].values  # gets values from 3 to 12 (remember that 13 is not included) # puts into numpy array
y = dataset.iloc[:,13].values # we put thirteen  for row thirteen here

dataset.head(5)

# now run this new code


column_trans = ColumnTransformer(
    [("countries", OneHotEncoder(), [1]),
    ("gender", OneHotEncoder(), [1])],
    remainder='passthrough'
)

# dummy variable trap
# you always omit one dummy variable. why is this? If you have 8, then you omit 1 and now have seven dummy variables
"""
Say you have male and female and you have two dummy variales. 1 if you
Multicolinearity is when you have variables that are highly correlated with each other
You want to avoid this

To avoid this get rid of constant or you can to m-1 dummy variables
https://www.youtube.com/watch?v=BMNuPwUD5EA
https://www.youtube.com/watch?v=9yl6-HEY7_s

"""
x_train = column_trans.fit_transform(X)

print(x_train)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
# splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 3)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Fitting classifier to the Training set
# create your classifier her

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making a confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)