LIN373 UT Austin :: Jessy Li

Original material from Byron Wallace

## Sentiment Analysis with Naive Bayes

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [2]:
from sklearn.datasets import load_files
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
###
# assumes you have downloaded the movie reviews data from Canvas 
# and unpacked into 'movie-reviews' parent directory!!!
dataset = load_files("movie-reviews/")
print("n_samples: %d" % len(dataset.data))

n_samples: 2000


In [4]:
type(dataset)

sklearn.utils.Bunch

In [5]:
print(dataset.data[0])

b"arnold schwarzenegger has been an icon for action enthusiasts , since the late 80's , but lately his films have been very sloppy and the one-liners are getting worse . \nit's hard seeing arnold as mr . freeze in batman and robin , especially when he says tons of ice jokes , but hey he got 15 million , what's it matter to him ? \nonce again arnold has signed to do another expensive blockbuster , that can't compare with the likes of the terminator series , true lies and even eraser . \nin this so called dark thriller , the devil ( gabriel byrne ) has come upon earth , to impregnate a woman ( robin tunney ) which happens every 1000 years , and basically destroy the world , but apparently god has chosen one man , and that one man is jericho cane ( arnold himself ) . \nwith the help of a trusty sidekick ( kevin pollack ) , they will stop at nothing to let the devil take over the world ! \nparts of this are actually so absurd , that they would fit right in with dogma . \nyes , the film is 

In [6]:
print(dataset.data[:10])

[b"arnold schwarzenegger has been an icon for action enthusiasts , since the late 80's , but lately his films have been very sloppy and the one-liners are getting worse . \nit's hard seeing arnold as mr . freeze in batman and robin , especially when he says tons of ice jokes , but hey he got 15 million , what's it matter to him ? \nonce again arnold has signed to do another expensive blockbuster , that can't compare with the likes of the terminator series , true lies and even eraser . \nin this so called dark thriller , the devil ( gabriel byrne ) has come upon earth , to impregnate a woman ( robin tunney ) which happens every 1000 years , and basically destroy the world , but apparently god has chosen one man , and that one man is jericho cane ( arnold himself ) . \nwith the help of a trusty sidekick ( kevin pollack ) , they will stop at nothing to let the devil take over the world ! \nparts of this are actually so absurd , that they would fit right in with dogma . \nyes , the film is

In [7]:
print(dataset.target[:10])

[0 1 1 0 1 1 1 1 1 0]


In [8]:
# generate train/test subsets
docs_train, docs_test, y_train, y_test = train_test_split(
    dataset.data, dataset.target, test_size = 0.2, random_state = None)

In [9]:
vectorizer = CountVectorizer(stop_words = "english")
X_train = vectorizer.fit_transform(docs_train)

In [10]:
print(len(vectorizer.get_feature_names()))

35836


In [11]:
print(vectorizer.get_feature_names()[:1000])

['00', '000', '0009f', '007', '05', '10', '100', '1000', '10000', '100m', '101', '102', '103', '104', '105', '106', '107', '108', '109', '10b', '11', '110', '111', '113', '1138', '114', '115', '117', '118', '11th', '12', '121', '122', '123', '125', '126', '127', '128', '129', '12th', '13', '130', '131', '132', '133', '135', '137', '139', '13th', '14', '1400', '143', '14th', '15', '150', '1500s', '150th', '151', '152', '1521', '153', '155', '1583', '1590', '15th', '16', '160', '1600', '1600s', '161', '165', '167', '1692', '16mm', '16x9', '17', '170', '1700s', '1709', '172', '175', '1773', '1794', '1799', '17th', '18', '180', '1800', '1800s', '1830s', '1839', '1847', '1862', '1865', '1869', '1871', '1885', '1888', '1896', '1898', '1899', '18th', '19', '1900', '1900s', '1903', '1908', '1912', '1913', '1914', '1919', '1920s', '1922', '1923', '1925', '1926', '1928', '1930', '1930s', '1932', '1933', '1934', '1935', '1937', '1938', '1939', '1940', '1940s', '1941', '1942', '1943', '1944', '194

In [12]:
print(X_train.toarray()[:10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
print(X_train[0])

  (0, 23918)	2
  (0, 15419)	7
  (0, 29713)	1
  (0, 2284)	1
  (0, 748)	1
  (0, 11560)	1
  (0, 23812)	4
  (0, 27240)	2
  (0, 1815)	8
  (0, 31475)	1
  (0, 24626)	1
  (0, 15435)	3
  (0, 32797)	1
  (0, 3346)	1
  (0, 10899)	2
  (0, 28854)	1
  (0, 5004)	1
  (0, 22100)	1
  (0, 35596)	1
  (0, 8829)	2
  (0, 20053)	1
  (0, 31496)	1
  (0, 17562)	1
  (0, 7539)	1
  (0, 8623)	2
  :	:
  (0, 13568)	1
  (0, 21870)	1
  (0, 35396)	1
  (0, 30899)	1
  (0, 32102)	1
  (0, 19183)	1
  (0, 15328)	1
  (0, 33097)	1
  (0, 2846)	1
  (0, 31148)	1
  (0, 29775)	1
  (0, 10606)	1
  (0, 17164)	1
  (0, 2082)	1
  (0, 5)	8
  (0, 2990)	1
  (0, 10044)	1
  (0, 13564)	1
  (0, 16472)	1
  (0, 20493)	1
  (0, 19576)	1
  (0, 23751)	1
  (0, 3557)	1
  (0, 29162)	1
  (0, 15105)	1


In [14]:
print(X_train.shape)

(1600, 35836)


In [15]:
# fit the model
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [16]:
# now test on the test set
X_test = vectorizer.transform(docs_test)
y_hat = model.predict(X_test)

In [17]:
print("accuracy is: ", metrics.accuracy_score(y_test, y_hat))

accuracy is:  0.8275


In [18]:
print("classification report: ", metrics.classification_report(y_test, y_hat))

classification report:                precision    recall  f1-score   support

           0       0.85      0.81      0.83       203
           1       0.81      0.85      0.83       197

    accuracy                           0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400

